// src/routes/cart/+page.svelte
<script lang="ts">
	import { cart } from '$lib/stores/cart';
	import type { CartItem } from '$lib/stores/cart';

	$: total = $cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);
	$: deliveryFee = 500;
	$: finalTotal = total + deliveryFee;

	function updateQuantity(id: string, change: number) {
		cart.updateQuantity(id, change);
	}

	function removeItem(id: string) {
		cart.removeItem(id);
	}
</script>

<svelte:head>
	<title>Cart - Lolidee's Cuisine</title>
	<meta name="description" content="View your cart at Lolidee's Cuisine. Review your order and proceed to checkout." />
</svelte:head>

<!-- Cart Header -->
<div class="horder">
	<h2>My Cart</h2>
	<div class="g">
		<a href="/cart"><i class="fa-solid fa-cart-shopping"></i> Cart({$cart.length})</a>
	</div>
</div>

<!-- Cart Items -->
<section class="ord">
	<section class="order">
		{#if $cart.length === 0}
			<div class="empty-cart">
				<p>Your cart is empty</p>
				<a href="/menu" class="btn">Browse Menu</a>
			</div>
		{:else}
			{#each $cart as item (item.id)}
				<div class="orders">
					<div class="img">
						<img src={item.image} alt={item.name}>
					</div>
					<div class="whole">
						<div class="one">
							<h3>{item.name}</h3>
							<button on:click={() => removeItem(item.id)} aria-label="Remove item">
								<i class="fa-regular fa-trash-can"></i>
							</button>
						</div>
						<div class="two">
							<h3>#{item.price.toLocaleString()}</h3>
							<div class="three">
								<button on:click={() => updateQuantity(item.id, -1)} aria-label="Decrease quantity">
									<i class="fa-solid fa-minus"></i>
								</button>
								{item.quantity}
								<button on:click={() => updateQuantity(item.id, 1)} aria-label="Increase quantity">
									<i class="fa-solid fa-plus"></i>
								</button>
							</div>
						</div>
					</div>
				</div>
			{/each}
		{/if}
	</section>
</section>

<!-- Order Summary -->
{#if $cart.length > 0}
	<section class="hub">
		<div class="delivery">
			<h2>Order Summary</h2>
		</div>

		<section class="process">
			<div class="sub">
				<h3>Subtotal</h3>
				<h3>#{total.toLocaleString()}</h3>
			</div>
			<div class="del">
				<h3>Delivery Fee</h3>
				<h3>#{deliveryFee.toLocaleString()}</h3>
			</div>
			<div class="pay">
				<h3>Total Payment</h3>
				<h3>#{finalTotal.toLocaleString()}</h3>
			</div>
			<a href="/payment" class="btn">Process Order</a>
		</section>
	</section>

	<!-- Checkout Button -->
	<div class="end">
		<a href="/payment" class="btn">Checkout</a>
	</div>
{/if}

<style>
    @import '/css/cart.css';

    /* Additional Svelte-specific styles */
    button {
        background: none;
        border: none;
        cursor: pointer;
        padding: 0;
        font-family: inherit;
    }

    .three button {
        display: inline-flex;
        align-items: center;
        justify-content: center;
    }

    .three button:hover {
        opacity: 0.8;
    }

    .one button {
        color: var(--color-2);
        transition: color 0.3s ease;
    }

    .one button:hover {
        color: var(--color-1);
    }

    .empty-cart {
        text-align: center;
        padding: 2rem;
    }

    .empty-cart p {
        margin-bottom: 1rem;
        color: var(--color-2);
    }

    .empty-cart .btn {
        display: inline-block;
        background: var(--color-1);
        color: var(--color-light);
        padding: 0.5rem 1rem;
        border-radius: 4px;
        text-decoration: none;
        transition: background-color 0.3s ease;
    }

    .empty-cart .btn:hover {
        background: var(--color-2);
    }
</style>

// react-lolidee-cuisine/src/pages/Cart.js
import React from 'react';
import { Link } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCartShopping, faPlus, faMinus, faTrashCan } from '@fortawesome/free-solid-svg-icons';
import { useCart } from '../context/CartContext';

const Cart = () => {
  const { 
    cartItems, 
    removeFromCart, 
    increaseQuantity, 
    decreaseQuantity, 
    getCartCount,
    getTotalPrice
  } = useCart();
  
  return (
    <>
      {/* Cart header */}
      <div className="horder">
        <h2>My Cart</h2>
        <div className="g">
          <Link to="/cart">
            <FontAwesomeIcon icon={faCartShopping} /> Carts({getCartCount()})
          </Link>
        </div>
      </div>
      
      {/* Cart items */}
      {cartItems.length === 0 ? (
        <div className="empty-cart">
          <h3>Your cart is empty</h3>
          <p>Add some delicious items to your cart</p>
          <Link to="/menu" className="btn">Browse Menu</Link>
        </div>
      ) : (
        <>
          <section className="ord">
            <section className="order">
              {cartItems.map(item => (
                <div key={item.id} className="orders">
                  <div className="img">
                    <img src={item.image} alt={item.name} />
                  </div>
                  <div className="whole">
                    <div className="one">
                      <h3>{item.name}</h3>
                      <FontAwesomeIcon 
                        icon={faTrashCan} 
                        onClick={() => removeFromCart(item.id)}
                        style={{ cursor: 'pointer' }}
                      />
                    </div>
                    <div className="two">
                      <h3>₦{(item.price * item.quantity).toLocaleString()}</h3>
                      <div className="three">
                        <FontAwesomeIcon 
                          icon={faMinus} 
                          onClick={() => decreaseQuantity(item.id)}
                          style={{ cursor: 'pointer' }}
                        />
                        {item.quantity}
                        <FontAwesomeIcon 
                          icon={faPlus} 
                          onClick={() => increaseQuantity(item.id)}
                          style={{ cursor: 'pointer' }}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </section>
          </section>
          
          {/* Order summary */}
          <section className="hub">
            <div className="delivery">
              <h2>Order Summary</h2>
            </div>
            <section className="process">
              <div className="sub">
                <h3>Subtotal</h3>
                <h3>₦{getTotalPrice().toLocaleString()}</h3>
              </div>
              <div className="del">
                <h3>Delivery Fee</h3>
                <h3>₦500</h3>
              </div>
              <div className="pay">
                <h3>Total Payment</h3>
                <h3>₦{(getTotalPrice() + 500).toLocaleString()}</h3>
              </div>
              <Link to="/checkout" className="btn">Process Order</Link>
            </section>
          </section>
        </>
      )}
    </>
  );
};

export default Cart;
