// src/routes/menu/+page.svelte
<script lang="ts">
    import { page } from "$app/stores";
    import Navbar from "../../components/Navbar.svelte";
    import Footer from "../../components/Footer.svelte";
    import MenuItem from "../../components/MenuItem.svelte";

    let activeCategory = 'all';
    let searchQuery = '';

    const categories = [
        { id: 'all', name: 'All' },
        { id: 'meals', name: 'Meals' },
        { id: 'swallow', name: 'Swallow' },
        { id: 'soup', name: 'Soups' },
        { id: 'extras', name: 'Extras' }
    ];

    const menuItems = {
        meals: [
            {
                id: 'smoky-jollof',
                name: 'Smoky Jollof Rice',
                image: '/images/images (73).jpeg',
                rating: 4.8,
                description: 'Freshly made and served hot, an healthy meal for all',
                price: 4000
            },
            {
                id: 'coconut-fried',
                name: 'Coconut Fried Rice',
                image: '/images/images (76).jpeg',
                rating: 4.8,
                description: 'Freshly made and served hot, an healthy meal for all',
                price: 4000
            },
            // Add more meal items...
        ],
        swallow: [
            {
                id: 'black-amala',
                name: 'Hot Black Amala',
                image: '/images/images (84).jpeg',
                rating: 4.8,
                description: 'Freshly made and served hot, an healthy meal for all',
                price: 4000
            },
            // Add more swallow items...
        ],
        soup: [
            {
                id: 'efo-riro',
                name: 'Sweet Efo Riro',
                image: '/images/images (85).jpeg',
                rating: 4.8,
                description: 'Freshly made and served hot, an healthy meal for all',
                price: 4000
            },
            // Add more soup items...
        ],
        extras: [
            {
                id: 'moi-moi',
                name: 'Hot moi moi',
                image: '/images/images (100).jpeg',
                rating: 4.8,
                description: 'Freshly made and served hot, an healthy meal for all',
                price: 4000
            },
            // Add more extra items...
        ]
    };

    function handleCategoryClick(category: string) {
        activeCategory = category;
    }

    function handleAddToCart(itemId: string) {
        // Implement cart functionality
        console.log('Adding to cart:', itemId);
    }

    function handleFavorite(itemId: string) {
        // Implement favorite functionality
        console.log('Toggling favorite:', itemId);
    }
</script>

<svelte:head>
    <title>Our Menu - Lolidee's Cuisine</title>
    <meta name="description" content="Explore our diverse menu featuring delicious meals, swallow, soups, and extras" />
</svelte:head>

<Navbar />

<!-- Menu Hero Section -->
<section class="menu-hero">
    <div class="container">
        <div class="menu-header">
            <h1>Our Menu</h1>
            <p>Our menu is like falling into a world of foodie fantasies. A culinary adventure waiting to be
                explored, with new flavors and taste around every corner. It's the perfect place to find your new
                favorite dish.</p>
        </div>
        <div class="menu-controls">
            <div class="search-bar">
                <i class="fas fa-search"></i>
                <input 
                    type="text" 
                    placeholder="Search for food..." 
                    bind:value={searchQuery}
                />
            </div>
            <a href="/cart" class="cart-button">
                <i class="fa-solid fa-cart-shopping"></i>
                <span class="cart-count">0</span>
            </a>
        </div>
    </div>
</section>

<!-- Category Navigation -->
<nav class="category-nav">
    <div class="container">
        <ul class="category-list">
            {#each categories as category}
                <li>
                    <a 
                        href="#{category.id}" 
                        class={activeCategory === category.id ? 'active' : ''}
                        on:click|preventDefault={() => handleCategoryClick(category.id)}
                    >
                        {category.name}
                    </a>
                </li>
            {/each}
        </ul>
    </div>
</nav>

<!-- Menu Sections -->
<main class="menu-sections">
    <div class="container">
        {#each categories as category}
            {#if activeCategory === 'all' || activeCategory === category.id}
                <section>
                    <h2 class="section-title">{category.name}</h2>
                    <div class="menu-grid">
                        {#each menuItems[category.id as keyof typeof menuItems] as item}
                            <MenuItem
                                imageSrc={item.image}
                                title={item.name}
                                description={item.description}
                                price={`#${item.price.toLocaleString()}`}
                                rating={item.rating}
                                cartItem={item.id}
                            />
                        {/each}
                    </div>
                </section>
            {/if}
        {/each}
    </div>
</main>

<Footer />

<style>
    @import 'static/css/menu.css';
</style>

// react-lolidee-cuisine/src/pages/Menu.js
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCartShopping } from '@fortawesome/free-solid-svg-icons';
import FoodItem from '../components/FoodItem';
import foodData from '../data/foodData';
import { useCart } from '../context/CartContext';

const Menu = () => {
  const [activeCategory, setActiveCategory] = useState('all');
  const [searchTerm, setSearchTerm] = useState('');
  const { getCartCount } = useCart();
  
  // Filter food items based on active category and search term
  const filteredItems = foodData.filter(item => {
    const matchesCategory = activeCategory === 'all' || item.category === activeCategory;
    const matchesSearch = item.name.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesCategory && matchesSearch;
  });
  
  return (
    <>
      {/* Menu header section */}
      <section className="ok">
        <div className="contain">
          <div className="row">
            <div className="section-title">
              <h2>Our Menu</h2>
              <p>
                Our menu is like falling into a world of foodie fantasies. A culinary adventure waiting to be explored, 
                with new flavors and taste around every corner. It's the perfect place to find your new favorite dish
              </p>
            </div>
          </div>
          <div className="search">
            <input 
              type="text" 
              placeholder="search for food" 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
            <div>
              <div className="j">
                <Link to="/cart">
                  <FontAwesomeIcon icon={faCartShopping} /> ({getCartCount()})
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      {/* Category navigation */}
      <section className="slide">
        <div className="discover">
          <h2>Discover</h2>
          <div className="all">
            <ul>
              <li>
                <a 
                  className={activeCategory === 'all' ? 'al' : ''} 
                  href="#" 
                  onClick={(e) => {
                    e.preventDefault();
                    setActiveCategory('all');
                  }}
                >
                  All
                </a>
              </li>
              <li>
                <a 
                  className={activeCategory === 'meals' ? 'al' : ''} 
                  href="#" 
                  onClick={(e) => {
                    e.preventDefault();
                    setActiveCategory('meals');
                  }}
                >
                  Meals
                </a>
              </li>
              <li>
                <a 
                  className={activeCategory === 'swallow' ? 'al' : ''} 
                  href="#" 
                  onClick={(e) => {
                    e.preventDefault();
                    setActiveCategory('swallow');
                  }}
                >
                  Swallow
                </a>
              </li>
              <li>
                <a 
                  className={activeCategory === 'soups' ? 'al' : ''} 
                  href="#" 
                  onClick={(e) => {
                    e.preventDefault();
                    setActiveCategory('soups');
                  }}
                >
                  Soups
                </a>
              </li>
              <li>
                <a 
                  className={activeCategory === 'extras' ? 'al' : ''} 
                  href="#" 
                  onClick={(e) => {
                    e.preventDefault();
                    setActiveCategory('extras');
                  }}
                >
                  Extras
                </a>
              </li>
            </ul>
          </div>
        </div>
      </section>
      
      {/* Food items display */}
      <div className="food">
        <div className="swallow">
          <h2>{activeCategory === 'all' ? 'All Items' : activeCategory.charAt(0).toUpperCase() + activeCategory.slice(1)}</h2>
          <section className="menuu">
            {filteredItems.map(food => (
              <div key={food.id} className="row menu-tab-content active">
                <FoodItem food={food} />
              </div>
            ))}
          </section>
        </div>
      </div>
    </>
  );
};

export default Menu;
